### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by mizzunet** [fushinari/Wordbook#31]
* Wordbook version: 0.3.1-3
* Python version: 3.10.2
* Operating System: Artix

### Description
Download do not start 

![image](https://user-images.githubusercontent.com/10193999/157927738-095714ce-8f57-4d82-852a-c76aa2a6d53d.png)

### What I Did
`wordbook`
```
Exception in thread Thread-1 (download):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/wordbook/wordbook/base.py", line 404, in download
    wn.download("ewn:2020", progress_handler=progress_handler)
  File "/usr/lib/python3.10/site-packages/wn/_download.py", line 72, in download
    _download(url, path, progress)
  File "/usr/lib/python3.10/site-packages/wn/_download.py", line 92, in _download
    progress.set(status='Requesting')
  File "/usr/lib/python3.10/site-packages/wn/util.py", line 102, in set
    self.update(0, force=True)
TypeError: ProgressUpdater.update() got an unexpected keyword argument 'force'
```

**Comment by mizzunet** [comment]
I installed from repo, and the it downloaded fine

**Comment by fushinari** [comment]
Sorry, this is either a packaging issue or wrong version of dependencies on manual install and there is nothing I can do about it.

0.3.1 needs `python-wn` v0.6.1 while `main` needs v0.8.0 . There is no stable API to conform to, so updating it to match it would make little sense compared to just freezing the dependency version.

The GTK4-based `restruct` branch works with the latest version of `python-wn` and will eventually be released when some issues are resolved (that are, sadly, also outside of my control).

**Comment by fushinari** [comment]
The `wordbook-git` package should work.

**Comment by Scosh** [comment]
![image](https://user-images.githubusercontent.com/5603235/175011436-c2336d15-fb7e-4ee2-a0f4-c3819018a09f.png)

hi!

love the idea for this app, it looks & feels like a big improvement over the standard gnome-dictionary!

unfortunately, i encountered this error on a fresh arch linux install as well and tried downloading the git version as recommended here, but the problem persists.

executing in terminal gives this:

```
$ wordbook
```

```
Exception in thread Thread-1 (_try_dl_wn):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/wordbook/wordbook/window.py", line 583, in _try_dl_wn
    self._wn_downloader.download(ProgressUpdater)
  File "/usr/share/wordbook/wordbook/base.py", line 359, in download
    wn.download("oewn:2021", progress_handler=progress_handler)
  File "/usr/lib/python3.10/site-packages/wn/_download.py", line 57, in download
    info = config.get_project_info(project_or_url)
  File "/usr/lib/python3.10/site-packages/wn/_config.py", line 130, in get_project_info
    project: Dict = self._projects[id]
KeyError: 'oewn'

(:34021): Gtk-WARNING **: 12:48:17.010: GtkText - did not receive a focus-out event.
If you handle this event, you must return
GDK_EVENT_PROPAGATE so the default handler
gets the event as well
```

i then tried building from source to use the main branch, but got errors during the build, too:

```
$ make setup
```

```
mkdir -p _build
meson . _build
The Meson build system
Version: 0.62.2
Source dir: /home/scosh/Downloads/Wordbook
Build dir: /home/scosh/Downloads/Wordbook/_build
Build type: native build
Project name: wordbook
Project version: 0.3.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Message: Looking for dependencies
Program python3 found: YES (/usr/bin/python3)
Message: Found python3 binary
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Found CMake: /usr/bin/cmake (3.23.2)
Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)

meson.build:23:0: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake

A full log can be found at /home/scosh/Downloads/Wordbook/_build/meson-logs/meson-log.txt
make: *** [Makefile:19: setup] Error 1
```
here’s that log:
[meson-log.txt](https://github.com/fushinari/Wordbook/files/8957032/meson-log.txt)

---

since i’m on gnome, i _then_ resorted to using the `software` app to install your app with flatpak as a workaround — but this obviously isn’t the preferred method with arch linux, since it would be nicer to have all installed apps be centrally managed with pacman and an aur helper.

still really love the interface though 💚 you did a really great job with it and that’s why i am now using it as my replacement for gnome-dictionary since i use the wordnet database there anyway. :)
